require("random_dir.remap")
require("random_dir.set")
require("random_dir.packer")
require("random_dir.undotree")
local colors = require("random_dir.colors")
-- colors.ColorMyPencils()
print("Hello, Osvaldo")
