-- This file is discontinued to avoid multiple setups of active lsps
--
-- require("mason").setup()
--
-- require("mason-lspconfig").setup({
--   ensure_installed = {
--     "pyright",          -- Python
--     "clangd",           -- C/C++
--     "jdtls",            -- Java
--     "ts_ls",            -- JavaScript/TypeScript
--     "sqlls",            -- SQL
--     "bashls",           -- Bash
--     "lua_ls",           -- Lua
--     "rust_analyzer",    -- Rust
--   },
-- })
--
